"""add tontine njangi tables

Revision ID: b3bcbd2cf6b4
Revises: 60a4a89d8c24
Create Date: 2026-07-26 23:32:31.083285

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b3bcbd2cf6b4'
down_revision: Union[str, Sequence[str], None] = '60a4a89d8c24'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tontine_groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('creator_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('contribution_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('frequency', sa.Enum('WEEKLY', 'BIWEEKLY', 'MONTHLY', name='tontinefrequency_enum'), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'COMPLETED', 'CANCELLED', name='tontinegroupstatus_enum'), nullable=False),
    sa.Column('current_cycle', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), server_default=sa.text('CURRENT_DATE'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tontine_groups_creator_id'), 'tontine_groups', ['creator_id'], unique=False)
    op.create_index(op.f('ix_tontine_groups_id'), 'tontine_groups', ['id'], unique=False)
    op.create_table('tontine_members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('display_name', sa.String(length=128), nullable=False),
    sa.Column('payout_position', sa.Integer(), nullable=False),
    sa.Column('has_received_payout', sa.Boolean(), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['tontine_groups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('group_id', 'payout_position', name='uq_tontine_member_position')
    )
    op.create_index(op.f('ix_tontine_members_group_id'), 'tontine_members', ['group_id'], unique=False)
    op.create_index(op.f('ix_tontine_members_id'), 'tontine_members', ['id'], unique=False)
    op.create_index(op.f('ix_tontine_members_user_id'), 'tontine_members', ['user_id'], unique=False)
    op.create_table('tontine_contributions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('cycle_number', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('status', sa.Enum('PAID', 'LATE', name='tontinecontributionstatus_enum'), nullable=False),
    sa.Column('transaction_id', sa.Integer(), nullable=True),
    sa.Column('paid_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['tontine_groups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['member_id'], ['tontine_members.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('member_id', 'cycle_number', name='uq_tontine_contribution_member_cycle')
    )
    op.create_index(op.f('ix_tontine_contributions_group_id'), 'tontine_contributions', ['group_id'], unique=False)
    op.create_index(op.f('ix_tontine_contributions_id'), 'tontine_contributions', ['id'], unique=False)
    op.create_index(op.f('ix_tontine_contributions_member_id'), 'tontine_contributions', ['member_id'], unique=False)
    op.create_table('tontine_payouts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('cycle_number', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('transaction_id', sa.Integer(), nullable=True),
    sa.Column('paid_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['tontine_groups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['member_id'], ['tontine_members.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('group_id', 'cycle_number', name='uq_tontine_payout_group_cycle')
    )
    op.create_index(op.f('ix_tontine_payouts_group_id'), 'tontine_payouts', ['group_id'], unique=False)
    op.create_index(op.f('ix_tontine_payouts_id'), 'tontine_payouts', ['id'], unique=False)
    op.create_index(op.f('ix_tontine_payouts_member_id'), 'tontine_payouts', ['member_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tontine_payouts_member_id'), table_name='tontine_payouts')
    op.drop_index(op.f('ix_tontine_payouts_id'), table_name='tontine_payouts')
    op.drop_index(op.f('ix_tontine_payouts_group_id'), table_name='tontine_payouts')
    op.drop_table('tontine_payouts')
    op.drop_index(op.f('ix_tontine_contributions_member_id'), table_name='tontine_contributions')
    op.drop_index(op.f('ix_tontine_contributions_id'), table_name='tontine_contributions')
    op.drop_index(op.f('ix_tontine_contributions_group_id'), table_name='tontine_contributions')
    op.drop_table('tontine_contributions')
    op.drop_index(op.f('ix_tontine_members_user_id'), table_name='tontine_members')
    op.drop_index(op.f('ix_tontine_members_id'), table_name='tontine_members')
    op.drop_index(op.f('ix_tontine_members_group_id'), table_name='tontine_members')
    op.drop_table('tontine_members')
    op.drop_index(op.f('ix_tontine_groups_id'), table_name='tontine_groups')
    op.drop_index(op.f('ix_tontine_groups_creator_id'), table_name='tontine_groups')
    op.drop_table('tontine_groups')
    # ### end Alembic commands ###
