"""
Mbamager Transaction Pydantic Schemas

This module defines Pydantic schemas for the Transaction model.
Enforces that monetary values must be Decimal, and amounts must be strictly positive.
Reuses existing TransactionDirection and TransactionCategory database enums.
"""

from datetime import datetime
from decimal import Decimal

from pydantic import Field

from app.models.transaction import TransactionCategory, TransactionDirection
from app.schemas.common import BaseSchema, TimestampSchema

class TransactionBase(BaseSchema):
    """
    Shared attributes representing a financial transaction.
    """
    # Amounts are always stored as positive decimal values.
    # TransactionDirection determines whether the amount represents an inflow (CREDIT) or an outflow (DEBIT).
    amount: Decimal = Field(
        ...,
        gt=Decimal("0"),
        description="Transaction amount. Must be a strictly positive decimal value."
    )
    fee: Decimal = Field(
        default_factory=lambda: Decimal("0.00"),
        ge=Decimal("0"),
        description="Fee associated with the transaction (e.g. operator withdrawal charges)."
    )
    direction: TransactionDirection = Field(
        ...,
        description="Classification of transaction direction (CREDIT, DEBIT)"
    )
    category: TransactionCategory = Field(
        ...,
        description="Categorization tag matching standard transaction domains"
    )
    narrative: str | None = Field(
        default=None,
        max_length=255,
        description="Optional narrative block (user note, SMS description, or AI summary)"
    )
    tx_id_external: str | None = Field(
        default=None,
        max_length=64,
        description="Operator Transaction ID Reference (e.g. telecom TxID)"
    )
    timestamp: datetime | None = Field(
        default=None,
        description="Actual time the financial event occurred. If omitted, the service layer assigns the current UTC timestamp."
    )

class TransactionCreate(TransactionBase):
    """
    Payload required to register a new transaction.
    """
    account_id: int = Field(..., description="Unique account identifier associated with this transaction")

class TransactionUpdate(BaseSchema):
    """
    Payload for updating an existing transaction. All fields are optional.
    """
    amount: Decimal | None = Field(
        default=None,
        gt=Decimal("0"),
        description="Positive transaction amount"
    )
    fee: Decimal | None = Field(
        default=None,
        ge=Decimal("0"),
        description="Fee associated with the transaction"
    )
    direction: TransactionDirection | None = Field(
        default=None,
        description="Classification of transaction direction (CREDIT, DEBIT)"
    )
    category: TransactionCategory | None = Field(
        default=None,
        description="Categorization tag"
    )
    narrative: str | None = Field(
        default=None,
        max_length=255,
        description="Optional narrative block"
    )
    tx_id_external: str | None = Field(
        default=None,
        max_length=64,
        description="Operator Transaction ID Reference"
    )
    timestamp: datetime | None = Field(
        default=None,
        description="Actual time the financial event occurred"
    )

class TransactionResponse(TransactionBase, TimestampSchema):
    """
    Public schema for returning transaction details.
    """
    id: int = Field(..., description="Unique auto-incrementing transaction identifier")
    account_id: int = Field(..., description="Unique account identifier associated with this transaction")
    ai_confidence: Decimal | None = Field(
        default=None,
        description="Confidence score generated by AI for transaction classification"
    )

class AlternativeCategory(BaseSchema):
    category: str = Field(..., description="Alternative transaction category option")
    confidence: float = Field(..., description="Confidence level for the alternative category")
    reason: str = Field(..., description="Reasoning or description for this alternative option")

class TransactionExplainResponse(BaseSchema):
    assigned_category: str = Field(..., description="Currently assigned category")
    confidence: float = Field(..., description="Confidence score of current category prediction")
    explanation: str = Field(..., description="Human-friendly text explaining why this category was assigned")
    alternatives: list[AlternativeCategory] = Field(..., description="Potential alternative category classifications")

class TransactionReclassifyResponse(BaseSchema):
    predicted_category: str = Field(..., description="Re-evaluated category prediction")
    confidence: float = Field(..., description="AI confidence score for the new prediction")

